import { AlertTriangle, CheckCircle2, Loader2, RefreshCw } from "lucide-react";
import type { ResponseSource, AnalysisStatus } from "@/contexts/AnalysisContext";

export function SourceBadge({ source, status }: { source: ResponseSource; status?: AnalysisStatus }) {
  const label = status === "LOADING" ? "LOADING" : source === "api" ? "API RESPONSE" : source === "unavailable" ? "API UNAVAILABLE" : "DEMO DATA";
  const tone = source === "api" ? "border-[#bdebdc] bg-[#effcf6] text-[#187957]" : source === "unavailable" ? "border-[#f4c6cd] bg-[#fff5f6] text-[#a94455]" : "border-[#bfe6ef] bg-[#eafbfd] text-[#28667d]";
  return <span className={`inline-flex items-center gap-2 rounded-full border px-2.5 py-1.5 text-[10px] font-mono uppercase tracking-[0.12em] ${tone}`}><span className={`size-1.5 rounded-full ${status === "LOADING" ? "animate-pulse bg-[#f5b942]" : source === "api" ? "bg-[#35d6a1]" : source === "unavailable" ? "bg-[#e85b6b]" : "bg-[#19c8e8]"}`} />{label}</span>;
}

export function DemoBanner({ onToggle, demoMode = true, source = "demo", status, error, onRetry }: { onToggle?: () => void; demoMode?: boolean; source?: ResponseSource; status?: AnalysisStatus; error?: string | null; onRetry?: () => void }) {
  const unavailable = source === "unavailable";
  return <div className={`flex flex-col gap-3 rounded-xl border px-4 py-3 text-xs ${unavailable ? "border-[#f4c6cd] bg-[#fff5f6] text-[#a94455]" : "border-[#bfe6ef] bg-[#eafbfd] text-[#28667d]"}`}><div className="flex flex-wrap items-center justify-between gap-3"><div className="flex items-start gap-2"><span className="mt-0.5 grid size-4 place-items-center rounded-full bg-[#19c8e8] text-[9px] font-bold text-[#07104b]">i</span><span><b className="font-semibold">{unavailable ? "API unavailable — the previous result was preserved." : demoMode ? "Demo mode is enabled — showing demonstration data." : "Live API mode is enabled."}</b> {error || "Sample values and alerts are clearly labeled for the hackathon MVP."}</span></div><div className="flex items-center gap-2"><SourceBadge source={source} status={status}/>{onToggle && <button onClick={onToggle} className="shrink-0 rounded-lg border border-[#9bd9e5] bg-white px-3 py-1.5 text-[10px] font-mono uppercase tracking-[0.1em] text-[#28667d] hover:bg-[#f4fdfe]">{demoMode ? "Switch to API" : "Enable demo mode"}</button>}{onRetry && unavailable && <button onClick={onRetry} className="inline-flex items-center gap-1 rounded-lg border border-[#f1bcc5] bg-white px-3 py-1.5 text-[10px] font-mono uppercase tracking-[0.1em] text-[#a94455] hover:bg-[#fffafb]"><RefreshCw size={12}/> Retry</button>}</div></div></div>;
}
export function LoadingState() { return <div className="flex items-center gap-2 py-10 text-sm text-[#68839b]"><Loader2 className="animate-spin text-[#19c8e8]" size={18}/> Running route intelligence…</div>; }
export function ErrorState({ message }: { message: string }) { return <div className="flex items-start gap-3 rounded-xl border border-[#f4c6cd] bg-[#fff5f6] p-4 text-sm text-[#a94455]"><AlertTriangle size={18} className="mt-0.5"/><div><div className="font-semibold">Analysis unavailable</div><div className="mt-1 text-xs">{message}</div></div></div>; }
export function SuccessState({ children }: { children: React.ReactNode }) { return <div className="flex items-center gap-2 rounded-xl border border-[#bdebdc] bg-[#effcf6] px-3 py-2 text-xs text-[#187957]"><CheckCircle2 size={15}/>{children}</div>; }
