import { Bell, Clock3, MapPin, ShieldAlert } from "lucide-react";
import { AppShell } from "@/components/AppShell";
import { DemoBanner } from "@/components/States";
import { SectionLabel } from "@/components/MetricCard";
import { demoAlerts } from "@/data/demoData";

export default function Alerts() {
  return <AppShell eyebrow="Workspace / disruptions" title="Alerts & disruptions"><div className="space-y-6"><DemoBanner/><div className="flex flex-col justify-between gap-4 sm:flex-row sm:items-end"><div><SectionLabel>Monitoring view</SectionLabel><p className="max-w-2xl text-sm leading-6 text-[#73869f]">Sample alerts demonstrate how an operator could triage route disruptions. No card below represents a verified real-world event.</p></div><div className="flex items-center gap-2 rounded-xl border border-[#d7e8f1] bg-white px-3 py-2 text-[10px] font-mono uppercase tracking-[0.12em] text-[#73869f]"><span className="size-1.5 rounded-full bg-[#f5b942]"/> 04 demo alerts</div></div><div className="grid gap-4 lg:grid-cols-2">{demoAlerts.map((alert, index) => <article key={alert.type} className="group rounded-2xl border border-[#d7e8f1] bg-white p-5 shadow-[0_10px_30px_rgba(11,46,83,0.04)] transition hover:-translate-y-0.5 hover:shadow-[0_16px_36px_rgba(11,46,83,0.08)]"><div className="flex items-start justify-between gap-4"><div className="flex items-start gap-3"><div className={`grid size-10 place-items-center rounded-xl ${alert.severity === "High" ? "bg-[#fff0f1] text-[#d74960]" : alert.severity === "Medium" ? "bg-[#fff8e8] text-[#c88717]" : "bg-[#e9fbf4] text-[#187957]"}`}><ShieldAlert size={18}/></div><div><div className="flex flex-wrap items-center gap-2"><h3 className="font-semibold capitalize text-[#102052]">{alert.type}</h3><span className="rounded-full border border-[#e7d5a7] bg-[#fffaf0] px-2 py-0.5 text-[9px] font-mono uppercase tracking-[0.1em] text-[#9a721e]">demo alert</span><span className="rounded-full bg-[#f1f5f8] px-2 py-0.5 text-[9px] font-mono uppercase tracking-[0.1em] text-[#73869f]">sample data</span></div><div className="mt-1 flex flex-wrap gap-3 text-[11px] text-[#73869f]"><span className="inline-flex items-center gap-1"><MapPin size={12}/> {alert.location}</span><span className="inline-flex items-center gap-1"><Clock3 size={12}/> {alert.time}</span></div></div></div><div className="text-right"><div className="font-mono text-[10px] uppercase tracking-[0.1em] text-[#73869f]">0{index + 1}</div><div className="mt-1 text-[10px] font-semibold uppercase text-[#3979f6]">{alert.status}</div></div></div><p className="mt-5 border-t border-[#edf3f6] pt-4 text-sm leading-6 text-[#5d748e]">{alert.description}</p></article>)}</div><div className="rounded-2xl border border-dashed border-[#b9dce8] bg-[#f8fcfd] p-8 text-center"><div className="mx-auto grid size-11 place-items-center rounded-full bg-[#e7f8fb] text-[#0b9db7]"><Bell size={19}/></div><h3 className="mt-4 font-semibold text-[#102052]">No live alert feed connected</h3><p className="mx-auto mt-2 max-w-md text-sm leading-6 text-[#73869f]">A production version can connect this view to a verified incident or weather source. Until then, sample cards stay labeled as demo.</p></div></div></AppShell>;
}
