import { Link } from "wouter";
import { ArrowRight, BrainCircuit, Check, ChevronRight, Clock3, CloudRain, MapPinned, Mountain, ShieldCheck, Sparkles, Waypoints } from "lucide-react";
import { BrandMark } from "@/components/BrandMark";

const features = [
  { icon: ShieldCheck, title: "Risk intelligence", text: "Combine accident, road-condition, and landslide signals in one clear view." },
  { icon: Waypoints, title: "Route recommendation", text: "Compare supplied corridors using a transparent prototype scoring formula." },
  { icon: Mountain, title: "Landslide monitoring", text: "Surface terrain exposure as a planning input, not a verified live incident." },
  { icon: MapPinned, title: "Road damage analysis", text: "Keep condition signals visible alongside distance and travel time." },
  { icon: Clock3, title: "ETA integration", text: "Make time a first-class route input for logistics operations." },
  { icon: BrainCircuit, title: "Explainable AI", text: "Trace every recommendation back to configured weights and inputs." },
];

export default function Landing() {
  return <div className="min-h-screen overflow-hidden bg-[#07104b] text-white">
    <header className="relative z-10 mx-auto flex max-w-7xl items-center justify-between px-5 py-6 sm:px-8 lg:px-10"><Link href="/"><BrandMark /></Link><nav className="hidden items-center gap-7 text-xs text-slate-300 lg:flex"><a href="#platform" className="transition hover:text-white">Platform</a><Link href="/dashboard" className="transition hover:text-white">Dashboard</Link><Link href="/route-analysis" className="transition hover:text-white">Route analysis</Link><Link href="/about" className="transition hover:text-white">About</Link></nav><div className="flex items-center gap-2 sm:gap-3"><Link href="/login" className="hidden rounded-lg px-3 py-2 text-xs text-slate-300 hover:text-white sm:block">Log in</Link><Link href="/dashboard" className="rounded-lg bg-[#19c8e8] px-3 py-2.5 text-xs font-semibold text-[#07104b] shadow-[0_8px_24px_rgba(25,200,232,0.22)] transition hover:-translate-y-0.5 hover:bg-[#5de0f2] sm:px-4">Get started <ArrowRight className="ml-1 inline" size={14}/></Link></div></header>
    <main>
      <section className="relative mx-auto grid max-w-7xl items-center gap-14 px-5 pb-20 pt-16 sm:px-8 lg:grid-cols-[1.02fr_.98fr] lg:px-10 lg:pb-28 lg:pt-20"><div className="pointer-events-none absolute -left-32 top-10 size-80 rounded-full bg-[#19c8e8]/10 blur-3xl"/><div className="relative z-10 max-w-2xl"><div className="mb-6 inline-flex items-center gap-2 rounded-full border border-cyan-300/20 bg-cyan-300/10 px-3 py-1.5 text-[10px] font-mono uppercase tracking-[0.16em] text-cyan-200"><span className="size-1.5 animate-pulse rounded-full bg-cyan-300"/> Northeast India · Phase 1 intelligence</div><h1 className="max-w-2xl text-[clamp(3.2rem,7vw,6.4rem)] font-semibold leading-[.92] tracking-[-0.075em] text-white">Intelligent logistics.<br/><span className="text-[#19c8e8]">Safer routes.</span><br/>Smarter decisions.</h1><p className="mt-8 max-w-xl text-base leading-8 text-slate-300 sm:text-lg">NAVEXA combines accident risk, road damage indicators, landslide exposure, and route scoring to support logistics planning across Northeast India.</p><div className="mt-9 flex flex-wrap gap-3"><Link href="/dashboard" className="rounded-xl bg-[#19c8e8] px-5 py-3.5 text-sm font-semibold text-[#07104b] transition hover:-translate-y-0.5 hover:bg-[#5de0f2]">Launch intelligence dashboard <ArrowRight className="ml-1 inline" size={16}/></Link><a href="#platform" className="rounded-xl border border-white/15 bg-white/[0.05] px-5 py-3.5 text-sm text-slate-200 transition hover:bg-white/10">Explore platform <ChevronRight className="ml-1 inline" size={16}/></a></div><div className="mt-8 flex items-center gap-3 text-[10px] font-mono uppercase tracking-[0.14em] text-slate-500"><Check size={14} className="text-[#35d6a1]"/> Prototype signals, clearly labeled · no fake live data</div></div>
      <div className="relative min-h-[440px] lg:min-h-[520px]"><div className="absolute inset-0 rounded-[32px] border border-cyan-300/15 bg-[#0c185e]/70 shadow-[0_30px_80px_rgba(0,0,0,0.24)] backdrop-blur-xl"/><div className="absolute inset-5 rounded-[24px] border border-white/10 bg-[radial-gradient(circle_at_50%_50%,rgba(25,200,232,.16),transparent_42%),linear-gradient(145deg,rgba(255,255,255,.03),transparent)]"/><svg viewBox="0 0 600 520" className="absolute inset-7 size-[calc(100%-56px)] overflow-visible"><defs><filter id="glow"><feGaussianBlur stdDeviation="5" result="coloredBlur"/><feMerge><feMergeNode in="coloredBlur"/><feMergeNode in="SourceGraphic"/></feMerge></filter></defs><path d="M50 370 C 130 260, 135 420, 230 290 S 375 270, 425 190 S 500 95, 560 130" fill="none" stroke="#19c8e8" strokeWidth="3" strokeDasharray="10 9" filter="url(#glow)"/><path d="M50 370 C 130 260, 135 420, 230 290 S 375 270, 425 190 S 500 95, 560 130" fill="none" stroke="#dff7fc" strokeWidth="1" opacity=".8"/><path d="M78 115 L205 170 L300 125 L420 220 L505 175" fill="none" stroke="#3979f6" strokeWidth="1.5" strokeDasharray="4 12" opacity=".6"/><path d="M305 42 L300 125 L230 290 L315 375 L345 490" fill="none" stroke="#a5e8f2" strokeWidth="1" opacity=".4"/>{[{x:50,y:370,label:"GUA",c:"#19c8e8"},{x:230,y:290,label:"SHL",c:"#35d6a1"},{x:425,y:190,label:"KOH",c:"#f5b942"},{x:560,y:130,label:"IMP",c:"#e85b6b"}].map((p)=><g key={p.label}><circle cx={p.x} cy={p.y} r="21" fill={p.c} opacity=".12"/><circle cx={p.x} cy={p.y} r="6" fill={p.c} stroke="#fff" strokeWidth="2"/><text x={p.x+12} y={p.y-12} fill="#cfeef4" fontSize="11" fontFamily="monospace">{p.label}</text></g>)}</svg><div className="absolute left-9 top-9 rounded-xl border border-white/10 bg-[#07104b]/75 px-3 py-2 backdrop-blur"><div className="flex items-center gap-2 text-[10px] font-mono uppercase tracking-[0.13em] text-cyan-200"><span className="size-1.5 animate-pulse rounded-full bg-cyan-300"/> Network layer / 01</div><div className="mt-1 text-[10px] text-slate-500">Illustrative corridor geometry</div></div><div className="absolute bottom-8 left-8 right-8 grid grid-cols-3 gap-2"><div className="rounded-xl border border-white/10 bg-white/[0.06] p-3"><div className="font-mono text-lg text-white">08</div><div className="mt-1 text-[9px] uppercase tracking-[0.12em] text-slate-500">regions</div></div><div className="rounded-xl border border-white/10 bg-white/[0.06] p-3"><div className="font-mono text-lg text-white">5×</div><div className="mt-1 text-[9px] uppercase tracking-[0.12em] text-slate-500">model inputs</div></div><div className="rounded-xl border border-white/10 bg-white/[0.06] p-3"><div className="font-mono text-lg text-[#19c8e8]">API</div><div className="mt-1 text-[9px] uppercase tracking-[0.12em] text-slate-500">ready</div></div></div></div>
      </section>
      <section id="platform" className="border-t border-white/10 bg-[#f4f9fc] px-5 py-20 text-[#102052] sm:px-8 lg:px-10 lg:py-28"><div className="mx-auto max-w-7xl"><div className="max-w-2xl"><div className="text-[10px] font-mono uppercase tracking-[0.18em] text-[#3979f6]">A planning layer for complex terrain</div><h2 className="mt-4 text-4xl font-semibold tracking-[-0.06em] text-[#0a1858] sm:text-5xl">From route inputs to a decision you can inspect.</h2><p className="mt-5 text-base leading-7 text-[#6d8098]">A focused Phase 1 experience for demonstrating how a unified route-analysis API can make risk signals legible to operators.</p></div><div className="mt-12 grid gap-4 sm:grid-cols-2 lg:grid-cols-3">{features.map(({ icon: Icon, title, text }) => <div key={title} className="group rounded-2xl border border-[#d7e8f1] bg-white p-5 shadow-[0_10px_30px_rgba(11,46,83,0.04)] transition hover:-translate-y-1 hover:shadow-[0_16px_38px_rgba(11,46,83,0.09)]"><div className="grid size-10 place-items-center rounded-xl bg-[#e5f8fb] text-[#0b9db7] transition group-hover:bg-[#19c8e8] group-hover:text-[#07104b]"><Icon size={19}/></div><h3 className="mt-5 font-semibold text-[#102052]">{title}</h3><p className="mt-2 text-sm leading-6 text-[#73869f]">{text}</p></div>)}</div></div></section>
    </main>
    <footer className="border-t border-white/10 bg-[#07104b] px-5 py-8 text-xs text-slate-500 sm:px-8 lg:px-10"><div className="mx-auto flex max-w-7xl flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div>© 2026 NAVEXA · Northeast India Regional Logistics Intelligence</div><div className="flex items-center gap-2 font-mono uppercase tracking-[0.12em]"><CloudRain size={13}/> prototype / not a safety guarantee</div></div></footer>
  </div>;
}
