import { demoResponse, locations } from "@/data/demoData";
import type { GeoPoint, LocationOption, RiskResponse, RouteAnalysisRequest, RouteGenerationResponse, RouteOption } from "@/types/api";

const API_BASE_URL = import.meta.env.VITE_API_BASE_URL || "http://127.0.0.1:8003";
const ROUTE_GENERATION_URL = import.meta.env.VITE_ROUTE_GENERATION_URL || `${API_BASE_URL}/generate-routes`;
const UNIFIED_URL = import.meta.env.VITE_ROUTE_ANALYSIS_URL || `${API_BASE_URL}/analyze-route`;
const COMBINED_RISK_URL = import.meta.env.VITE_COMBINED_RISK_URL || "http://127.0.0.1:8001/combined-risk";
const RECOMMENDATION_URL = import.meta.env.VITE_API_BASE_URL ? `${import.meta.env.VITE_API_BASE_URL}/recommend-route` : "http://127.0.0.1:8002/recommend-route";

export class ApiRequestError extends Error { constructor(message: string, public kind: "timeout" | "network" | "server" | "invalid") { super(message); this.name = "ApiRequestError"; } }
function numberValue(value: unknown, fallback = 0) { const parsed = Number(value); return Number.isFinite(parsed) ? parsed : fallback; }
function validPoint(lat: number, lng: number) { return Number.isFinite(lat) && Number.isFinite(lng) && Math.abs(lat) <= 90 && Math.abs(lng) <= 180; }
function point(value: unknown, order: "latlng" | "lonlat" = "latlng"): [number, number][] | undefined { if (!Array.isArray(value)) return undefined; const points = value.map((item) => { if (Array.isArray(item)) { const first = numberValue(item[0]); const second = numberValue(item[1]); return (order === "lonlat" ? [second, first] : [first, second]) as [number, number]; } const object = (item || {}) as Record<string, unknown>; return [numberValue(object.lat), numberValue(object.lng ?? object.lon)] as [number, number]; }).filter(([lat, lng]) => validPoint(lat, lng)); return points.length > 1 ? points : undefined; }
function routeValue(value: unknown, index = 0, order: "latlng" | "lonlat" = "latlng"): RouteOption { if (typeof value === "string") return { route_name: value, distance: 0, travel_time: 0, risk_score: 0, status: "Recommended" }; const route = (value || {}) as Record<string, unknown>; const routeOrder = String(route.coordinate_order ?? route.geometry_order ?? order) === "lonlat" ? "lonlat" : "latlng"; return { route_name: String(route.route_name ?? route.name ?? `Route ${String.fromCharCode(65 + index)}`), distance: numberValue(route.distance ?? (numberValue(route.distance_meters) / 1000)), travel_time: numberValue(route.travel_time ?? route.travel_time_minutes ?? (numberValue(route.duration_seconds) / 60)), risk_score: numberValue(route.risk_score ?? route.risk), calculated_score: numberValue(route.calculated_score ?? route.route_score ?? route.score), status: String(route.status ?? "Available alternative"), geometry: point(route.geometry ?? route.coordinates ?? route.route_geometry, routeOrder) }; }
function locationValue(value: unknown, fallback?: LocationOption): LocationOption | undefined { if (!value && fallback) return fallback; const object = (value || {}) as Record<string, unknown>; const lat = numberValue(object.lat); const lng = numberValue(object.lng ?? object.lon); if (!validPoint(lat, lng)) return fallback; return { name: String(object.name ?? fallback?.name ?? "Location"), region: String(object.region ?? fallback?.region ?? "Northeast India"), lat, lng }; }

export function normalizeGeneratedRoutes(input: unknown): RouteGenerationResponse { const raw = (input || {}) as Record<string, unknown>; const rawRoutes = Array.isArray(raw.routes) ? raw.routes : Array.isArray(input) ? input : []; const order = String(raw.coordinate_order ?? raw.geometry_order) === "lonlat" ? "lonlat" : "latlng"; const routes = rawRoutes.map((route, index) => routeValue(route, index, order)); const status = routes.length === 0 ? "empty" : routes.length === 1 ? "single" : "available"; return { routes, status, message: String(raw.message ?? (status === "single" ? "Only one route alternative was returned by the routing service." : "")) }; }

export function normalizeRiskResponse(input: unknown, request?: RouteAnalysisRequest, generated?: RouteGenerationResponse): RiskResponse { const raw = (input || {}) as Record<string, unknown>; const nestedAnalysis = (raw.risk_analysis && typeof raw.risk_analysis === "object" ? raw.risk_analysis : {}) as Record<string, unknown>; const components = (raw.component_scores && typeof raw.component_scores === "object" ? raw.component_scores : nestedAnalysis.component_scores && typeof nestedAnalysis.component_scores === "object" ? nestedAnalysis.component_scores : {}) as Record<string, unknown>; const weights = (raw.weights && typeof raw.weights === "object" ? raw.weights : {}) as Record<string, unknown>; const rawRoutes = Array.isArray(raw.all_routes) ? raw.all_routes : Array.isArray(raw.routes) ? raw.routes : generated?.routes ?? []; const order = String(raw.coordinate_order ?? raw.geometry_order) === "lonlat" ? "lonlat" : "latlng"; const routes = rawRoutes.map((route, index) => routeValue(route, index, order)); const recommendation = routeValue(raw.recommended_route ?? raw.route_recommendation); const recommended = routes.find((route) => route.route_name === recommendation.route_name) ?? recommendation; if (!routes.length || !recommended.route_name) throw new ApiRequestError("The analysis service returned no usable route results.", "invalid"); const fallbackOrigin = locations.find((item) => item.name === request?.origin); const fallbackDestination = locations.find((item) => item.name === request?.destination); return { status: String(raw.status ?? "success"), risk_analysis: typeof raw.risk_analysis === "string" ? raw.risk_analysis : String(nestedAnalysis.summary ?? "Risk components returned by the analysis service."), overall_risk_score: numberValue(raw.overall_risk_score ?? nestedAnalysis.overall_risk_score ?? raw.risk_score), risk_category: String(raw.risk_category ?? nestedAnalysis.risk_category ?? "Medium") as RiskResponse["risk_category"], component_scores: { accident: numberValue(components.accident ?? components.accident_risk), road_damage: numberValue(components.road_damage ?? components.road_damage_risk), landslide: numberValue(components.landslide ?? components.landslide_risk) }, weights: { accident: numberValue(weights.accident ?? weights.accident_weight), road_damage: numberValue(weights.road_damage ?? weights.road_damage_weight), landslide: numberValue(weights.landslide ?? weights.landslide_weight) }, route_recommendation: typeof raw.route_recommendation === "string" ? raw.route_recommendation : `Recommended route: ${recommended.route_name}`, recommended_route: recommended, all_routes: routes, disclaimer: String(raw.disclaimer ?? demoResponse.disclaimer), origin: locationValue(raw.origin, fallbackOrigin), destination: locationValue(raw.destination, fallbackDestination), route_generation: generated };
}

async function postJson(url: string, body: unknown) { const controller = new AbortController(); const timeout = window.setTimeout(() => controller.abort(), 8000); try { const response = await fetch(url, { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(body), signal: controller.signal }); if (!response.ok) throw new ApiRequestError(response.status >= 500 ? "The analysis service returned a server error." : "The analysis service rejected the request.", "server"); let json: unknown; try { json = await response.json(); } catch { throw new ApiRequestError("The analysis service returned an invalid response.", "invalid"); } return json; } catch (error) { if (error instanceof ApiRequestError) throw error; if (error instanceof DOMException && error.name === "AbortError") throw new ApiRequestError("The request timed out. Check that the FastAPI server is running.", "timeout"); throw new ApiRequestError("Unable to retrieve route alternatives. Please try again.", "network"); } finally { window.clearTimeout(timeout); } }

export async function generateRoutes(origin: GeoPoint, destination: GeoPoint): Promise<RouteGenerationResponse> { if (!validPoint(origin.lat, origin.lng) || !validPoint(destination.lat, destination.lng)) throw new ApiRequestError("The selected coordinates are invalid. Choose the locations again.", "invalid"); const result = normalizeGeneratedRoutes(await postJson(ROUTE_GENERATION_URL, { origin, destination, alternatives: 2 })); if (result.status === "empty") throw new ApiRequestError("Unable to retrieve route alternatives. Please try again.", "invalid"); return result; }
export async function analyzeRoute(request: RouteAnalysisRequest, demoMode = true): Promise<{ data: RiskResponse; source: "demo" | "api" }> { if (demoMode) { await new Promise((resolve) => window.setTimeout(resolve, 450)); return { data: demoResponse, source: "demo" }; } if (!request.origin_coords || !request.destination_coords) throw new ApiRequestError("Origin and destination coordinates are required.", "invalid"); const generated = await generateRoutes(request.origin_coords, request.destination_coords); const body = { ...request, origin: { name: request.origin, ...request.origin_coords }, destination: { name: request.destination, ...request.destination_coords }, routes: generated.routes }; return { data: normalizeRiskResponse(await postJson(UNIFIED_URL, body), request, generated), source: "api" }; }
export async function getCombinedRisk(body: unknown) { return normalizeRiskResponse(await postJson(COMBINED_RISK_URL, body)); }
export async function recommendRoute(body: unknown) { return normalizeRiskResponse(await postJson(RECOMMENDATION_URL, body)); }
